from aisci_domain_paper.prompts.templates import (
    ALGORITHM_SYSTEM_PROMPT,
    BASELINE_SYSTEM_PROMPT,
    ENV_SETUP_SYSTEM_PROMPT,
    EXPERIMENTS_SYSTEM_PROMPT,
    EXPERIMENT_SYSTEM_PROMPT,
    EXPLORE_SYSTEM_PROMPT,
    GENERAL_SYSTEM_PROMPT,
    IMPLEMENTATION_SYSTEM_PROMPT,
    MAIN_AGENT_SYSTEM_PROMPT,
    PAPER_READER_SYSTEM_PROMPT,
    PLAN_SYSTEM_PROMPT,
    PRIORITIZATION_SYSTEM_PROMPT,
    RESOURCE_DOWNLOAD_SYSTEM_PROMPT,
    SEARCH_EXECUTOR_PROMPT,
    SEARCH_STRATEGIST_PROMPT,
    STRUCTURE_SYSTEM_PROMPT,
    SYNTHESIS_SYSTEM_PROMPT,
)


def load_paper_system_prompt() -> str:
    return MAIN_AGENT_SYSTEM_PROMPT


__all__ = [
    "ALGORITHM_SYSTEM_PROMPT",
    "BASELINE_SYSTEM_PROMPT",
    "ENV_SETUP_SYSTEM_PROMPT",
    "EXPERIMENTS_SYSTEM_PROMPT",
    "EXPERIMENT_SYSTEM_PROMPT",
    "EXPLORE_SYSTEM_PROMPT",
    "GENERAL_SYSTEM_PROMPT",
    "IMPLEMENTATION_SYSTEM_PROMPT",
    "MAIN_AGENT_SYSTEM_PROMPT",
    "PAPER_READER_SYSTEM_PROMPT",
    "PLAN_SYSTEM_PROMPT",
    "PRIORITIZATION_SYSTEM_PROMPT",
    "RESOURCE_DOWNLOAD_SYSTEM_PROMPT",
    "SEARCH_EXECUTOR_PROMPT",
    "SEARCH_STRATEGIST_PROMPT",
    "STRUCTURE_SYSTEM_PROMPT",
    "SYNTHESIS_SYSTEM_PROMPT",
    "load_paper_system_prompt",
]
