"""
Shared constants for the MLE-Bench AI Scientist agent.

Mirrors PaperBench's ``constants.py`` — centralised workspace reference tables
tailored to each agent's role.
"""

# ====================================================================== #
# Main Agent Workspace Reference (2-column — orchestrator knows everything)
# ====================================================================== #

MAIN_AGENT_WORKSPACE_REFERENCE = """## Workspace Reference

| Path | Content |
|------|---------|
| `/home/data/` | Competition dataset (train/test CSVs, images, etc.) |
| `/home/data/description.md` | Competition description — goals, evaluation metric, data format |
| `/home/data/sample_submission.csv` | Sample submission showing expected format |
| `/home/code/` | Your working code repository (git) |
| `/home/submission/submission.csv` | Final submission file (REQUIRED for grading) |
| `/home/submission/submission_registry.jsonl` | Append-only JSONL: system snapshot rows + **your** `candidate_detail` / `champion_selected` rows (method, metrics, eval protocol, rationale) |
| `/home/agent/analysis/summary.md` | Created by `analyze_data`: dataset overview and strategy |
| `/home/agent/prioritized_tasks.md` | Created by `prioritize_tasks`: ordered task list |
| `/home/agent/impl_log.md` | Implementation changelog (appended by implement subagent) |
| `/home/agent/exp_log.md` | Experiment log (appended by experiment subagent) |
| `/home/agent/experiments/` | Experiment output logs: `[task_id]/[run_id].log` |
| `/home/submission/candidates/` | Immutable snapshots after implement/run_experiment |"""


# ====================================================================== #
# Implementation Agent Workspace Reference (3-column with Availability)
# ====================================================================== #

IMPLEMENTATION_WORKSPACE_REFERENCE = """## Workspace Reference

| Path | Content | Availability |
|------|---------|--------------|
| `/home/data/` | Competition dataset (train/test CSVs, images, etc.) | Always |
| `/home/data/description.md` | Competition description — goals, evaluation metric, data format | Always |
| `/home/data/sample_submission.csv` | Sample submission showing expected format | Always |
| `/home/code/` | Code repository (git) — **your workspace** | Always |
| `/home/submission/submission.csv` | Final submission file (REQUIRED for grading) | Generated by your code |
| `/home/submission/candidates/` | Snapshot copies of `submission.csv` (written when the **main** agent finishes `implement` / `run_experiment`) | May appear while you run; paths belong in Candidate handoff |
| `/home/submission/submission_registry.jsonl` | JSONL log of snapshots + optional `candidate_detail` / `champion_selected` (main agent appends) | Optional read; you **report** handoff in `subagent_complete`, not edit this file unless asked |
| `/home/agent/analysis/summary.md` | Dataset analysis: shapes, types, distributions, strategy | After `analyze_data` |
| `/home/agent/prioritized_tasks.md` | Priority-ranked task list (P0-P3) | After `prioritize_tasks` |
| `/home/agent/impl_log.md` | Implementation changelog | Appended by you via `add_impl_log` |
| `/home/agent/exp_log.md` | Experiment results log | Appended by experiment subagent |
| `/home/agent/experiments/` | Experiment output logs: `[task_id]/[run_id].log` | Created by experiment subagent |

**Tip**: Use `ls` or `test -f <path>` to verify a file exists before reading it."""


# ====================================================================== #
# Experiment Agent Workspace Reference (3-column with Availability)
# ====================================================================== #

EXPERIMENT_WORKSPACE_REFERENCE = """## Workspace Reference

| Path | Content | Availability |
|------|---------|--------------|
| `/home/data/` | Competition dataset (train/test CSVs, images, etc.) | Always |
| `/home/data/description.md` | Competition description — goals, evaluation metric, data format | Always |
| `/home/data/sample_submission.csv` | Sample submission showing expected format | Always |
| `/home/code/` | Code repository (git) | Always |
| `/home/submission/submission.csv` | Final submission file (REQUIRED for grading) | May not exist yet |
| `/home/submission/candidates/` | Historical submission snapshots | May be empty early |
| `/home/submission/submission_registry.jsonl` | JSONL registry for candidates / champion metadata | Optional reads for context |
| `/home/agent/analysis/summary.md` | Dataset analysis | After `analyze_data` |
| `/home/agent/prioritized_tasks.md` | Priority-ranked task list (P0-P3) | After `prioritize_tasks` |
| `/home/agent/impl_log.md` | Implementation changelog | Appended by implement subagent |
| `/home/agent/exp_log.md` | Experiment results log | Appended by you via `add_exp_log` |
| `/home/agent/experiments/` | Experiment output logs: `[task_id]/[run_id].log` | Created by `exec_command` |

**Tip**: Use `ls` or `test -f <path>` to verify a file exists before reading it."""


# ====================================================================== #
# Generic Subagent Workspace Reference
# ====================================================================== #

SUBAGENT_WORKSPACE_REFERENCE = """## Workspace Reference

| Path | Content |
|------|---------|
| `/home/data/` | Competition dataset (train/test CSVs, images, etc.) |
| `/home/data/description.md` | Competition description |
| `/home/data/sample_submission.csv` | Sample submission format |
| `/home/code/` | Code repository (git) |
| `/home/submission/submission.csv` | Final submission file |
| `/home/submission/candidates/` | Snapshot copies of submission (after main agent `implement` / `run_experiment`) |
| `/home/submission/submission_registry.jsonl` | JSONL: system snapshot rows; main agent may append `candidate_detail` / `champion_selected` |
| `/home/agent/analysis/summary.md` | Dataset analysis summary |
| `/home/agent/prioritized_tasks.md` | Priority-ranked task list |
| `/home/agent/impl_log.md` | Implementation changelog |
| `/home/agent/exp_log.md` | Experiment results log |
| `/home/agent/plan.md` | Implementation plan |"""
